In [53]:
import numpy as np
import pandas as pd
import matplotlib as plt

df = pd.read_csv(r"C:\Users\jayak\OneDrive\Desktop\Data Analytics\Missingvalex.csv")

In [54]:
df.info

<bound method DataFrame.info of     ID             Name   Age    Salary   Department  Experience
0    1         John Doe  28.0   50000.0  Engineering         5.0
1    2       Jane Smith  35.0   60000.0    Marketing         8.0
2    3  Michael Johnson   NaN   45000.0  Engineering         7.0
3    4      Emily Davis  22.0   52000.0        Sales         NaN
4    5     Chris Wilson  45.0  120000.0  Engineering        20.0
5    6     Ashley Brown   NaN   54000.0        Sales         3.0
6    7        David Lee  38.0       NaN    Marketing        10.0
7    8      Linda White  50.0   70000.0  Engineering        25.0
8    9      James Green  40.0  130000.0        Sales        18.0
9   10     Susan Harris  31.0   55000.0        Sales         NaN
10  11     Robert Clark  33.0   62000.0    Marketing        12.0
11  12       Mary Allen  27.0   48000.0  Engineering         4.0
12  13     Charles King  46.0   70000.0  Engineering        22.0
13  14   Patricia Young  37.0   65000.0        Sales      

In [55]:
print(df.isnull().sum())

ID            0
Name          0
Age           3
Salary        2
Department    0
Experience    2
dtype: int64


In [56]:
# USING MEAN to fill missing values, We can do same for median and mode

uds_df = df
uds_df['Age']= uds_df['Age'].fillna(df['Age'].mean())
uds_df['Salary']= uds_df['Salary'].fillna(df['Salary'].mean())
uds_df['Experience']= uds_df['Experience'].fillna(df['Experience'].mean())

In [57]:
uds_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          20 non-null     int64  
 1   Name        20 non-null     object 
 2   Age         20 non-null     float64
 3   Salary      20 non-null     float64
 4   Department  20 non-null     object 
 5   Experience  20 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.1+ KB


In [58]:
uds_df.info

<bound method DataFrame.info of     ID             Name        Age         Salary   Department  Experience
0    1         John Doe  28.000000   50000.000000  Engineering    5.000000
1    2       Jane Smith  35.000000   60000.000000    Marketing    8.000000
2    3  Michael Johnson  35.058824   45000.000000  Engineering    7.000000
3    4      Emily Davis  22.000000   52000.000000        Sales   10.833333
4    5     Chris Wilson  45.000000  120000.000000  Engineering   20.000000
5    6     Ashley Brown  35.058824   54000.000000        Sales    3.000000
6    7        David Lee  38.000000   69222.222222    Marketing   10.000000
7    8      Linda White  50.000000   70000.000000  Engineering   25.000000
8    9      James Green  40.000000  130000.000000        Sales   18.000000
9   10     Susan Harris  31.000000   55000.000000        Sales   10.833333
10  11     Robert Clark  33.000000   62000.000000    Marketing   12.000000
11  12       Mary Allen  27.000000   48000.000000  Engineering    4.

In [59]:
#BACKWARD Filling Technique to fill missing values, we can do same for FORWARD Filling Technique

df1 = df
df1['Age']= df['Age'].bfill()
df1['Salary']= df['Salary'].bfill()
df1['Experience']= df['Experience'].bfill()

In [60]:
df1.info

<bound method DataFrame.info of     ID             Name        Age         Salary   Department  Experience
0    1         John Doe  28.000000   50000.000000  Engineering    5.000000
1    2       Jane Smith  35.000000   60000.000000    Marketing    8.000000
2    3  Michael Johnson  35.058824   45000.000000  Engineering    7.000000
3    4      Emily Davis  22.000000   52000.000000        Sales   10.833333
4    5     Chris Wilson  45.000000  120000.000000  Engineering   20.000000
5    6     Ashley Brown  35.058824   54000.000000        Sales    3.000000
6    7        David Lee  38.000000   69222.222222    Marketing   10.000000
7    8      Linda White  50.000000   70000.000000  Engineering   25.000000
8    9      James Green  40.000000  130000.000000        Sales   18.000000
9   10     Susan Harris  31.000000   55000.000000        Sales   10.833333
10  11     Robert Clark  33.000000   62000.000000    Marketing   12.000000
11  12       Mary Allen  27.000000   48000.000000  Engineering    4.

In [61]:
# FEATURE SCALING

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [62]:
new_df = pd.DataFrame(df,columns = ['Age','Salary','Experience'])

In [63]:
scaler = MinMaxScaler()
df_1 = scaler.fit_transform(new_df)
print(df_1)

[[0.21428571 0.04761905 0.09090909]
 [0.46428571 0.14285714 0.22727273]
 [0.46638655 0.         0.18181818]
 [0.         0.06666667 0.35606061]
 [0.82142857 0.71428571 0.77272727]
 [0.46638655 0.08571429 0.        ]
 [0.57142857 0.23068783 0.31818182]
 [1.         0.23809524 1.        ]
 [0.64285714 0.80952381 0.68181818]
 [0.32142857 0.0952381  0.35606061]
 [0.39285714 0.16190476 0.40909091]
 [0.17857143 0.02857143 0.04545455]
 [0.85714286 0.23809524 0.86363636]
 [0.53571429 0.19047619 0.5       ]
 [0.25       0.07619048 0.09090909]
 [0.46638655 0.05714286 0.13636364]
 [0.21428571 0.03809524 0.04545455]
 [0.32142857 1.         0.27272727]
 [0.42857143 0.23068783 0.22727273]
 [0.71428571 0.16190476 0.54545455]]


In [20]:
scaler = StandardScaler()
df_2 = scaler.fit_transform(new_df)
print(df_2)

[[-1.03131459 -0.67650526 -0.9398217 ]
 [-0.00859429 -0.32456611 -0.45648483]
 [ 0.         -0.85247483 -0.61759712]
 [-1.90793198 -0.60611743  0.        ]
 [ 1.45243471  1.7870688   1.47686268]
 [ 0.         -0.5357296  -1.26204629]
 [ 0.42971441  0.         -0.13426024]
 [ 2.18294921  0.02737305  2.28242414]
 [ 0.72192021  2.13900795  1.15463809]
 [-0.59300589 -0.50053568  0.        ]
 [-0.30080009 -0.25417828  0.18796434]
 [-1.17741748 -0.74689309 -1.100934  ]
 [ 1.59853761  0.02737305  1.79908726]
 [ 0.28361151 -0.14859653  0.51018893]
 [-0.88521169 -0.57092351 -0.9398217 ]
 [ 0.         -0.64131134 -0.77870941]
 [-1.03131459 -0.71169917 -1.100934  ]
 [-0.59300589  2.84288625 -0.29537254]
 [-0.15469719  0.         -0.45648483]
 [ 1.01412601 -0.25417828  0.67130122]]
